POST http://localhost:4500/project 
Content-Type: application/json

{
    "project_name":"Build a Mansion at Pwani",
    "description":"Build a Giant mansion",
    "project_location":"Nyeri Coast",
    "startdate":"24-07-2023",
    "enddate":"21-08-2025"
}


###
GET http://localhost:4500/project


###
GET http://localhost:4500/project/11eb8fc2-ca12-4164-8f0d-19f0e90319ef


###UPDATING PROJECT
PUT http://localhost:4500/project/b29d7593-db56-47b3-904f-320bb0518ef3
Content-Type: application/json

{
    "project_name":"Build a Tarmac Road",
    "description":"i am creating a tarmac road from nyeri to thika",
    "project_location":"Thika",
    "startdate":"2023-07-19",
    "enddate":"2023-06-11"
}

###DELETING PROJECT
DELETE http://localhost:4500/project/b29d7593-db56-47b3-904f-320bb0518ef3