POST http://localhost:4500/project 
Content-Type: application/json

{
    "project_name":"Build a Mansion at Pwani",
    "description":"Build a Giant mansion",
    "project_location":"Nyeri Coast",
    "startdate":"24-07-2023",
    "enddate":"21-08-2025"
}


###
GET http://localhost:4500/project


###
GET http://localhost:4500/project/5692e677-0c4f-4879-9c54-4bc2827b5ca4


###UPDATING PROJECT
PUT http://localhost:4500/project/bc8dd031-2ced-4089-ac26-03a89dc70f39
Content-Type: application/json

{
    "project_name":"Build a Tarmac Road",
    "description":"i am creating a tarmac road from nyeri to thika",
    "project_location":"Thika",
    "startdate":"2023-07-19",
    "enddate":"2023-06-11"
}

###DELETING PROJECT
DELETE http://localhost:4500/project/1fde31db-a319-4bca-9cc6-23a83225a1d8